### ISSUE TITLE
privateリポジトリでの利用 (Qiitaより)

### ISSUE THREAD

**Issue by k-shirakata** [lamact/react-issue-ganttchart#84]
Qiitaで質問させた頂いたものです．
テスト環境として，GitHub上でprivateリポジトリを作成しました．
また，アクセストークンの取得では，
- repo
- wtire:discussion
- read:org
にチェックを入れて作成しました． (これらにチェックを入れることで自動で入るチェックは外しておりません)

その後，yarn startを実行し，http://localhost:3000/react-issue-ganttchartがブラウザで自動で開きました．
開いたページの Git Repository URL の欄に作成したリポジトリのURLを，Access Token の欄に生成されたアクセストークンをそれぞれペーストしました．
この状態でチャートの画面から当該リポジトリにissueを作成し，yamlで期間等を記載しました．
label, assignee を指定しない状態でブラウザ更新をすると，403エラーが示され，作成したissueはチャートおよびチャート左側一覧の双方で表示されない状況です．

指摘や助言をいただければと思います．

**Comment by yhzz** [comment]
@k-shirakata すみません、GitHubのPrivateリポジトリはそもそも対応しておりませんでした。  
#73 でも言及がありニーズがあるようなので実装しました。ご確認ください。

**Comment by k-shirakata** [comment]
ありがとうございます．
動作確認できました!
